version: "3"

services:
  injectived:
    image: osmolabs/injective:10.0.1
    user: $UID:$GID
    volumes:
      - ./config:/injective/.injectived/config
      - ./data:/injective/.injectived/data
      - ./wasm:/injective/.injectived/wasm
    command:
      - start
    ports:
      - "26657:26657"
      - "1317:1317"
      - "9090:9090"
      - "9091:9091"
